---
apiVersion: v1
kind: Service
metadata:
  name: &service hass
  namespace: networking
spec:
  ports:
    - port: &port 8123
      protocol: TCP
      targetPort: *port
      name: http

---
apiVersion: v1
kind: Endpoints
metadata:
  name: *service
  namespace: networking
subsets:
- addresses:
  - ip: 192.168.99.224
  ports:
  - port: *port

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/target: external.calzone.zone
  name: *service
  namespace: networking
spec:
  ingressClassName: external
  rules:
  - host: &host hass.calzone.zone
    http:
      paths:
      - backend:
          service:
            name: *service
            port:
              number: *port
        path: /
  tls:
  - hosts:
    - *host
