# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:ANPNn/b2hpiZD1FXXak7VKC4DaAwgZsnhOJJfQo46dQfw19POQld3oJup46i1rmqeyjp7x+ofYOTSPPvNHM4YXiwBobW0icLE1IW+l6l5+sT4VX/4ImxQ4STCRUhF83cJVbytE7bYk77CBxnxGCyw/WPG05r0UWzkgafHUqs4tpXlVktnFdcBn3y6UO2AYe07zJsegNpvSbaianLAT4lXMzmu8uelBI/hkOF+mYoJg==,iv:MsZ7t9j+bbrwVlbpr2CRYhXNoijTBw7dC32teReeLgo=,tag:o+TMG5oiJDd2GZ63SwSPWA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zhs8q2mkfm6a8pr6qlkklcgjkqzunluud63kr2z8vswk0v5u93esp4kj8e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUHltS2Zxdnd2U1Z4V0VW
        ajJ4eFJuQlBPa2FXNDIwYWxHd3VpSGZOSUQ4Ck1laVlicXdZMllMcHY1MGdDL0Nu
        UDZZaTNEdEJPdFJtWTdNaFA3MDVLcVkKLS0tIFBhb3owMmNRcUdJaXZVVmhBWlFW
        dUVMZVdsVjhjQmJqWkg3elY4UWl1SU0KuiLCoeWNLx2psq8XvYowP4fVEx9w/egu
        PLd1BZSWZk8Mw+eEpxnEZsAKDn3VEHYrA22GZOHZ1ix+K5NXJ0swVw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T04:27:29Z"
  mac: ENC[AES256_GCM,data:xIQk/gztMhn71XrDtXPA/umik0gOS9fdJdCBMLnfwCD24effTEMxmjO9N/FhyVy/jvYoS3WhQhEUHFD5T1HNdBFxRvmO58mzUp/GcqMl6kRYWusmjfU0x38y1iYHAPgY+UpxXbb4LjAz/nSXQ/u/uaDHASIw8o6LZwWCW02LVJA=,iv:FKWAqp8Y+xnLCOt0fZbys7DIu6xOQpoIlL8W76KhZQw=,tag:lc/DJRWGxq5MJRzwBOWMSA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
