# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:otlUnn2x9K6vbxpqFJ6yO243yv03+iahvP3+70mgVe73XOjhGnJWD3cfpdWzes4jdhblpbtT7QOvY0ndo2dla5QsDTrNqZrL3ORUsAyc0DraotQRNYaQo5b6BtZCjDi2qA9tdUOtOnQVQ/Qonvkk8BUC/uopPcdbY8PhSpZ5UTmKXXVR5sfbiPfXAvbOnC9gUZC2uDuFXTg8Q5e7rHMgvTAwuMLbdnR4wC2OQY3loA==,iv:bfZ7YpPmLl8HejQkgsv5Lz6kN0LirutMV0vzDZBGer0=,tag:o2OSOylt6tpyCKehWXkwYA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zhs8q2mkfm6a8pr6qlkklcgjkqzunluud63kr2z8vswk0v5u93esp4kj8e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArb2pPSkQ2bzVxNmw3YVdr
        S0JYSmczTC9FMm9XMG52SlJLY0FLdFZZaG1nCjJsYktRYUYxMTV2WHlBLzZVSHUx
        WlRyVEVwWGVEN2ZzK3N2QTN5aDJpWkUKLS0tIGNCU2piMDNjMW5ITmI5MURRUFdN
        WUlUM2NSS0VFdVhaOWoycDNKTnVNSGMKGuifbZg7PM93lQRYgn5fV+97ilTT6svk
        Msu1uPWF5iEhM/vZAAC8Bw8gtfMDJ0Ba8Y5XzgTc4+3uhEP7Zj/pnQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T03:49:17Z"
  mac: ENC[AES256_GCM,data:hCAwfaGJiYgWn4lxqpXNLjStFVOcHTOKCyBISwpBCreZL591JmStyCpVP9fR82f/rOBQWO9epfBKpERclZhXyEIbqm+HW9fpUBElcGpeROV3XheG8cfST/pQpyp5MVyG07zxat6zBeAWby2jaYrbAFUdGJZ3qn/FjLy09KfaYCg=,iv:Kyo4vapItgvjx2i0mhG1W4/D4053+brDVFeAouOEhnY=,tag:MqurchjKaCtmKajvPhYuhw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
