# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:cITGHjFA5OgambDXEN//yjA/3EldCsyntk1tOmqGbt58JKkGALHXF4Tfjf6776Z5UojnyDRRFojgJJZnu+s2yNBMky44ccbTXi85okXO8AgOGf4AixfPFbo/3r2Mtye/r3RzvaT6jRCpFHNhDr9iLaOnE3RSInvA7W5lzXPZXnztZC0Dp32a9KBOGTZJtL0PleT6oKQQkOVKwUNikjAX+4qKNcPnxArk0j8GAPR2hQ==,iv:eNxcCJAVCcj1ibxrG3DYVeLNtsRQX4Sd7DV7Q5EfUXs=,tag:73bICgdJHpWmyhinyEf1pA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zhs8q2mkfm6a8pr6qlkklcgjkqzunluud63kr2z8vswk0v5u93esp4kj8e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MitHVWp6RnBRbmZsd1ZB
        UnNML09USXlJN3Z4N1BCYlhQZ2Q3dVp0QWs0Ckp3SHBDNWpIMGxpUlpZTklCOHNX
        Mzd4RVJldXFzZG5HVUNaNEpGZjF1WHMKLS0tIFR5T2NITEFOVWdzOEE2L3pqNjNl
        YjRjUmlRaHFWMEQwdjZDYWkzS2lReUkKldUub5xGkT8SWeBryQghq3ZLFH/f8jFk
        N5rlttTjfL9jXcJ2/uVicQRriinv1jJGxchbDyGe6CxJRXWYZwJUXQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T03:15:31Z"
  mac: ENC[AES256_GCM,data:ZgvBSIocplvxKQf0WiAjSu2CtL14L1AwjmLvH/8yaZpeCjJUnsPXyQiFCQ64j4U/rsygQFNpidaWHaDWZTKExyU42717Q+e/TF/FerGdIoc4jyYv/W0aRgAgdzSKM9gABxZaur1OU2+MYCryUy7yeqMA7O6zXc5hfwUug9W1kI4=,iv:mZXyZ8/QaRS+zMg6qM+tMGgWjT/bDEtlB+QtfxzwS0M=,tag:VOH1Qh/KEtDkPK+VTqUfMA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
