# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:lRcMoZu+YlpSAFx8qEOz05OYhEe3uYBXuUxU/EFe0EO1x+Xn9X7JCw==,iv:ekC7wJVOP8wwKZ1yoYqJSEYc599cqLUELm3U3z/dLaE=,tag:WLuoOFQJtNnZXfeyHKE5Cg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zhs8q2mkfm6a8pr6qlkklcgjkqzunluud63kr2z8vswk0v5u93esp4kj8e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVzV2MmNaUmswRXdIUkd2
        K0dud3Z3dVFBa3E0R1Z0UzgvMk5xcUpDWENNClZSSGtaSmIvQS8zb0RBdzNzMndU
        QUZ1SDRZckNGRUFWTU4yMGhKQUtabHMKLS0tIGNFMVQ0dlZwK1EweW9GMGtwQlFK
        MkF2Z1R4aEVyZTFiVW5pc2xUSk9RdkkKDpOoSB/10MsPs7RWy5IFoHROzRSSwvyg
        nrvkGdXUzslNuD7+uvc0B6rlgz8QNrAsnt/559sv7mptGj1MAu7WNg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T03:15:31Z"
  mac: ENC[AES256_GCM,data:fk8RVsuL4Aze/jwzN3892lNJZMIH0ic1acpxx5nogP66MS4Pe2FzTpvr3akdeNkocZjn0MgWChohfccaEaBSk95vxaYKz15Uzwi1WqpHmpDA4ZLleC9NdoBJFcju4ZQw/G2net9I4ijZtqitAw8sVbSUqVnadO3y3Uafb3uttCQ=,iv:z4IWd4ZtfN7Yz8Q27MmgQX5rNLdVFeJRPuTXPRYUSl0=,tag:w2NkVHemAXwL763acmZFfw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
