# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:UQG1aUEBiNdHsZfjtcnAatFApgxAcL9FrlZOcsbelL9layPgBJDlCg==,iv:uZWGosVabQ2aDFW+o7gdQqOvklLh/ZVs6b7ObER4PtU=,tag:8Oh9xoUgXVbYYiqVumZ8oA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zhs8q2mkfm6a8pr6qlkklcgjkqzunluud63kr2z8vswk0v5u93esp4kj8e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOFYxMEMrUHRIdFJFRmJG
        YTBjQW9kUXBnaEJ5V0IxVVBOMjdUSWcxdEdNCkR2UjBDajVIZXR4UUk3MEdWejcr
        SUpEUi8vYjJaYjdQZ1pzdHUwU1o5UVEKLS0tIEpORHNnNVkxNVZJRWZUamVETWRT
        THRocU1WbGltZlJ3emZEUzFMd2xyekUKg2l+XOPbnrln1FH2KB9QDQuQ62WbLhj0
        Sl7doE4Vlbtc5z1LalnpFvsAmmkEplJMugsqo45J/nJRlW5hNBCFUQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T03:49:17Z"
  mac: ENC[AES256_GCM,data:XBErLbCHM7P60H96DOqyuY32KZj9n+ivPmbN24lxH7B+GyTTxKtl+6NMm7yPdrJNXNhAmN0dabRJQzTrVBdrnAONUwTEuu2ocjlM+pEdLl1Dw6tAElVF7ittIP1lvfIjtG23jKU5ep9bO8KRXh7lP3ote+5Bf+3TJzPUPkBq/Rs=,iv:BsFuG3fUA1jr7Xul53YBAQAqwpNgBNeO9LQaCXa1kQU=,tag:fJJvJ3veSAKhR+5bEmTv7g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
