# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:az5G23GAL0dJArzMWV0ZPjqAYyAaHox2XTbDOWF4T3pRszGLdwmRIQ==,iv:VoYE86CYRTRZV8NeGsosFtQspVbyU1iupXRTSt2F52Q=,tag:2Dpp4QZLbFD7ASuegX6gsw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zhs8q2mkfm6a8pr6qlkklcgjkqzunluud63kr2z8vswk0v5u93esp4kj8e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlelFyVXBJOGQvbkJtMXJV
        Zm1IWlNRNU9GbzhXMmhSLy9uNFVrZDc5NURRCkdYeVJMTS95My9CbXQ4Ky9ieUhX
        N0NVd21hanJXUUVUVXNrTHlUNkoyeTQKLS0tIEpocVM2VFNmQTZJeTRtNTZzNnlG
        Z0x3TTVTb05EZ3dPQzFyWVRFeEtDemcKNZZex0JSE+6+hcUUBWO2gutTcD84BUZZ
        1oAbXcO7A5e0UcsIzTPTo5f6B3lBfDmMo3ghvJOeZ+dmz3CsR0Aq5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T04:27:29Z"
  mac: ENC[AES256_GCM,data:GPo64bn+n0GP0EcUAyH3s7RvHuy+MpCC/ytLmxp3Sk7NvPgFsaqj8z0GDJ4X+66KMFwHkvCssotRHHTU0AnzfA5AhKZCpizB2X6p5irT0pKiBeYGxyApYiD1wYu1aBiwLYSZocCDA2uxe9MvXZmVkSuZ2RdLEZ5q3Oe07aU9Vqs=,iv:9L+ndQhvB8Xj6BLy0XFGoFlsH7QbYiVNSoD1cGssgqI=,tag:DiqPb4yG8/KyvsGsmtnP8w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
