ansible_become_pass: ENC[AES256_GCM,data:1JiObcuNQ7F+Gw==,iv:slFIaxqZ4unlkJ2U6zbQTV/Q/Ez895hzieVfbohycK4=,tag:LKagmFxkvj9nkeexi4KL1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdGVkQUloLzJIeEZJaSs1
            UkI0TmoycTV4RnR5L1E3cmpUa2wyQ29RbVhrCndNdjBaeVUxU2lCZklHT0hnWVZW
            MVRDRkR2a2JmRlM2bnc3bzlFNFkyU28KLS0tIDU4MHl4b053cERzN2h6bDY3UlRE
            a3BxNzJkRllqWXlHdlFMQlFnREYrWlEKJVCg7ijUc92eP5qxT82VyFKnGO79nM7S
            2cZnU6pRmCGiiaDq4lRGSntZREydGHxig5jNmETGS0w5k7IUlqSI+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T19:06:22Z"
    mac: ENC[AES256_GCM,data:uEZap18pZTlKjMK9NaYnedSojU7HDI7wnhC1gu2HuRJAkuNOki6ObTIJN2XG63guV3dyFcC2l/9TUUuTFd3eG/8eijXrDXJBf2yN4dW8o1FyoOgyyEcKjaQsg0P2KFm0IamSQ62PWqiFAR+QQNcbxyLejX/ggBUhenhoTbBjfhA=,iv:e9nN21usV93QowAWsLJK7KVDLkBSlwoYsQcUkJYJb40=,tag:n/pQ4YGGtOUS6gPQm/SCVA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
