ansible_become_pass: ENC[AES256_GCM,data:tNmDcpYXq2k7OA==,iv:zxlj2V44JWGkbHGVk5bA64Z/2QFBPR5vw5tgtWuXVZM=,tag:rL+i6TvLCSERwe6GZZnOEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdzUrbzZneHZhSEN3djBr
            Rm9UTHA5QmhRK1ZmU2wzL3ZpYW1CZ3JmcndBCkZmcTg4SFJteVA3T3NLT2FmTWM0
            YzZ4a2ovOTBqOWhZV3BteDJaaWNybE0KLS0tIGlQNnE2SkRIWGttNE9qUnV2V2J4
            UHFyUkp2MENRWnBVTHR5QkdZK0xibTQKp13qXlJpl8QWVW3PVW7np5Qa56cHnBVZ
            Yneh/f93O7qWADViqKMFh/xQobrzuMvqNF3Dn48XasGW5KoVb69brQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:45:36Z"
    mac: ENC[AES256_GCM,data:CmHH5aexwB62RSpRxIHDg9VKpCktwk/JWbPYDyO0PAjgl1FlgC7Fsc7/rM93i9YwCYZyHUbYFso+JTNRcjrRbLucTDX35hfd3Vq2bIXwt51F4ewdhXQilIrPVphJp5IVGO/NNtn71Suud9mcHetC2SA+TUKttn7eThc0CE7RjqE=,iv:OWRTqAYAcD8GeMXZVpMOK9cC0ZxpNe3Fctdy7mzxGwc=,tag:c5xoqu97tXYop9EHsIkmZA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
