ansible_become_pass: ENC[AES256_GCM,data:x9O6X6rDZlr4kw==,iv:vLmJwQO3U4AZX/HkEN9zYMFms4QpSCsfhZzTPI6zSvQ=,tag:kA5zeX2NgVnlce3nno0Yvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVmF0cjYwVmpXVExkQUp5
            MGV5VWtWUmNhUkpWTWdNREYyN3l2MW1IeFVnCkFHRkJ1aDhRNFRwdmhVWjFYNTIr
            V0tIVDczUUVLS29pU3dpVU01UkFGdlUKLS0tIEkzbTMrYURlM2o1OEgrYjdYdXZJ
            N0ZhbS8zSU9BUEhPVStVV1NLSWlqbVEKfRhLCBxhTKAkLU+xKP0oHZ8mhAwRY3lS
            6nhOD0Jy6dyqCsQzOdmUvZEhaRRw8jaGw8+B2ACD04o6nzz8JEJXJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:45:36Z"
    mac: ENC[AES256_GCM,data:7N3wNMf8R/MDoa1G+QDfAi8YKTVdSNbpGxxBzD9E3n1+5HMNMboCyIgW7kBAVpF6+LllUlNJp3MSJyUpXpFqpRixVg9hS0HiREvepkPmmssRXvzO0VBG7lPCiqdMj4R0zDGo9p9xiq8Yu6oQsDmvmRPDamBslLFypR0ui1ms4S8=,iv:NY29IBrM9ZgCrjILrzfYnUINbLQnADkUnEIpg3KuxF4=,tag:eOlyTOdqG5Fl+A2oAs75Nw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
