ansible_become_pass: ENC[AES256_GCM,data:yT53oy46vp7bLA==,iv:YJJmsGc5phlHB/oONhZmY7kkVKPpAZMuR7b0a2KYskk=,tag:QnPmy2nRKPMmK1W0WHxbKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TkFENHJFUXIrcC9xaEYy
            Q1krbkU3a0NORXpvakxndGFTbE9Qc1M1ZXpZClJsRWVUQVBaS1liQmRud0g1WDlj
            Qm1KaUpPdWsrLzFZYms1TE9kK1JxMFEKLS0tIGFxY1duMmg4V2pXU1RFWk9RSUJN
            ejlqL1BVMC9iVnBlMTMvNHphMThyZXMK52Sio6kLRU8H1tNm+/qzzSXIeyws9OLs
            3UsCc8zxdca8tfB17nHy13as6b1hxEsExkoH6728p8jsP5K7bel87w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:24:39Z"
    mac: ENC[AES256_GCM,data:Tn0ATRsk0/7B4kxU44GUDTNSRj96YrjesOuG5p5u6fhnZ8KdYKW1Yl1J98Xr3+Mu8BrbC6TXxcjyY2kGQ6n77ZuoaJSIKGpxZkfDeFUrs1/zVxpilNxtC8TUUsF++nJ5OIdrjs6S866h7JLLWF/cfHoh8JcojI+ET7nNTk9Ulkg=,iv:esnP6BAiOoKGD491Or7RSQNM7F6fKkO6+opLogkYq5w=,tag:tXzUMFUK7u7zo+xEMv3CnQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
