ansible_become_pass: ENC[AES256_GCM,data:p9dZOIo5oy+fKw==,iv:EkZPnP3H7rHTGuUs2jpnuZUcLwwzGDOdUMpmvJq41CQ=,tag:OGsm6ZTJoTrQPCR6nkGhyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdHF1b3BVbFh3TUpMdHdP
            TUJnSkMwY1owWWRRTVp0ZS9KdGtGRXcyMGxNCnJBSTY2elF3ZWdlMEpGcTNteUhV
            RGl4c1dTRVZodEFuTzRtdmNYOE56SEEKLS0tIC9ab1ZnZFdwTVdXZjAvUHlKck11
            NjNvakxVVzJiYS9FMlNUZ1RsWWQ5WDQKFreWyjwb02xC0FHYb9r0ZFMmIgfbqHW7
            c5qpu6RPiMm4dLyx+3+YVoNcWAE+8liiKOAEh1/0PnaaThlqWxugig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:24:39Z"
    mac: ENC[AES256_GCM,data:8rU54ZkLnOwJ5ln6wsv98cVKPaCPuV60VmTtyeoRJmwGnwKtrL6KGyYCRc6umxJg+SL62OURxIPR7RJ1tQHjt0AHp5sMq/V66GXAThuH/VNAtcQRkQ8DqNznCv+BJdpwVIQ3mC9pWJ+Vye767cKva5MLpHcRtXcMOL8fkaxpVUU=,iv:no6sVaORA2O/yWVujfhcxgvhFviqLaKq/Mmf9nB8iA4=,tag:sh7nXd9Uf0h6Z0MMJOBwpw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
