ansible_become_pass: ENC[AES256_GCM,data:/hFSKvZPfVsNXg==,iv:pumzZFhegrcaQuQ5xU02y1G+PJIsXxSYr616v7vl/7Q=,tag:Z/Ops7OVDCIl5h8XxGvkKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpd2N5T212MkNtdVREUXZj
            cEZaekpIaDN3MzBCbmUvMXpsa0gybFE0clJFCldZamhJYkZyVmwrdTR2TzNzaFI5
            dzhHSmE4YUY4MGdWYVQySHBDaWJkY1EKLS0tIGE0elBkazI0R3hGN3p3VkNxOXVi
            cTNOZVpxYnpaK0Yxd0c4ZXhuZ0RzVTQKGvSkzH7EPFR0QXwjl46AB4NL1WY6ZGD6
            klea4nSquvt1ukvHaR+OymwgsxDO+Rtw0xR4qFm623YN3KaKIimDRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T19:06:23Z"
    mac: ENC[AES256_GCM,data:+C18/VSb+MSIZ1oDmCLMDqd72A8pp3qDUpUlGBaPL/svwSmarEtpd4+AMOK725Tt9U5p3pL02udXTHDwuEjqS9wgGyoamxV0fgQwNfwPOVGuwhK9j75fZ37ViccXP9IaDMFDhqUhJOihAP7AkyBL6s5r8y5Cwg/TYliKPW1OB28=,iv:5WAjJjJOBakVOQp86zSp8RmSptRK1mLejE8+Vs9Eqhs=,tag:+yGgpK3tMkl5GCEkKqP9PQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
