ansible_become_pass: ENC[AES256_GCM,data:DQkfQohE57E7MA==,iv:Co+YtFDRQWu6xOY/zGDgm56oKd4TQ1S6zG0mIQKQR6c=,tag:+Nzg/55c7SDAz10M1FZv6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQy9CR0t3bUlucVovdERv
            WWh1ai9rZFNDWXlpU2NtWjQxL05PWmxDemhFCmxpaXJpU0pZSnRMM3hUT0xzdVJo
            WU40aGQxc3pCZnc0NUtkdjJjcklwNGMKLS0tIEtMRlN4VmQvL3RmcXFLdUJ4ZWFr
            MHdQem1XWEZhRURycTc2OVA4ZFp0UkkK2LwAblMeYfBUJhTzldILZGUkExNqUmqq
            LH5kUYDJWrVy5VXJdkBZVdnnry7uU/72BT1+Zl9ExR+IAWp+Mxo54g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:45:36Z"
    mac: ENC[AES256_GCM,data:SfBkUoJX2rzA2L3/nA6SH/jG5rCI38PGB1KPq7W5W2BZ34iLELbJZM0NkcjxU5AO02lGklEK0yzM47kkIQL9Vy6mRNSUTdojPAGT+kpOTrKyCSDBuppbCMRBp6GRAFZD0520B8EE0GuWIhAVymfAGPYATQgThDsHc8v/uRp0jvo=,iv:syX1qaIZ60/BrvSSLGwAmUbNoN6w/1e+qEg5TumGDSw=,tag:6TPezz2wQ664qds+EcmUHg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
