ansible_become_pass: ENC[AES256_GCM,data:6NRiGp7g43xO7g==,iv:jcCD18b3KRp4NmtR3x4mpORc29GN1xGM53lO6xGuTqg=,tag:cTVPDJfD5BeJPJTVTEW1Mw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQ0NpYzI0ZVFUZ3A5c1BK
            R2Y5YTRRN0R1c0ZQY3ZvQ3lHTmU5QUhEbmtjCnB2S0FPNFltR0ZmWTZnY2tOb1pH
            eTh4MlJCaTI2WVpkTWpBcTM1SXJzNGcKLS0tIGlVRGtqUzAvd0dONFRTMjRyMWIw
            R1BrTG8ra254NjEycHNxTmxQNG4zMHcKaUNZm0i4aeZj6tIZVlIHxpanOrrQIhH8
            PPYs/v61GajlXXPolVkv8Zau17ZYrMOatB8a4iW6T0exxiVwb886zQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:24:38Z"
    mac: ENC[AES256_GCM,data:PmmV8dNUfS2WCFLPmlYrbI0pTVSZBRRMc/LeLFmkeZVGkTMzxRMA1wmKGaopHFOBPKIg3K+DCGEMtFYx/pDPgb3iqcczmWKigu+cdLo5lEj1BZu7gn8QOApoDzczsu2udON5+BVDM3KFPqZePWbdpFu3NFPU2nKAPGFgacpDsf4=,iv:i3rwe3n1jhazl8Yd0kKpYsBTDcNnYS7GSJxQsyYJn0Y=,tag:CTRKP/18TCzP4M6WsuANVg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
