ansible_become_pass: ENC[AES256_GCM,data:/4XmtlIOrdYNMg==,iv:Fo9CfMiDR+dp92NlMa5UYPkizT48Ho5qgNdRxic8EcE=,tag:0IbDUGSQd3QW9DOVqpxXUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtaGNuTkJQOXVTUkNya3VV
            Tmd2aUdzTFRFN0ZUck9RTHFvMXhNbzFaSFRjCnZYdUZsNnlYdUZ0NUtKdnhkUFNx
            MEEzSDJtMmtPMUNuK2trUGdxMXdVbEUKLS0tIDIwdlBGSCtKVHhJZzZNV1NmWFNR
            QkZ0TTR3OUpjQzR5NjYzajFCSHpBazQK0rQ9LxRV2LO9Yleu9sMbDTBt7EqLCRtN
            rVDB/8h+pitwkyNi1ERA3V3+4j92xUMWI1cJFRY8jttsVeZHuLeylQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:45:36Z"
    mac: ENC[AES256_GCM,data:4KN5foOyj7fLnAmMh4Xs712LW4sxbUTKspd+oQPoi43Ck5CJBD1Iv6Qn4Vc9uHISfYh9R4/tQj3Ckq433z6KEu7wnpRIvcg5TDKyOEr4zc0rO8AwwIEBhF4Z+PfW9sZxQat0XLnGDlDLpqdkUtbhQ2PqZ85HXaEbisiNh72u0ew=,iv:uMQnZKJ9iqIlx1GlLRu+R6DBXeYT2/uCYNuZGXV4ht4=,tag:w8YYGo9RCf6ZkY7ZVRWPUw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
