ansible_become_pass: ENC[AES256_GCM,data:ZgYlrDjc0NrNCQ==,iv:ualXimFQ25G5BcEFvC21qsLIKbqb40TT60Zx1LMrr+c=,tag:YiqhxH39b0SG4SxKT3XLaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaHBiWE5RU2xuYUFLWEJG
            ek5maHFwRGdRNDAyWEpZM0c0VUZYaFlTS1RzCnp0WUYzNUhUNGV3U3piUXZWVW44
            SncvV1JSSXF1UUJKU0JTSDFjbG1mWWcKLS0tIHlueTlDdkZNRlRrT3NoUFJhOXNV
            c3NtWSt1QUpuUGw5TGF6c2owa0xDOGcKs2dRzQyELy9ffZM09Hy0pMnCN7aJut+9
            RhLqLDzQJxTTY4vgcjfHpnLat3o5YDC6wIX/moMcqv4Ym6VPGe+w8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:24:38Z"
    mac: ENC[AES256_GCM,data:85ofXt+sRUjr/OXOwvOD6KWAUFjmNakseDvhwW29Wgb8bbW3OHNhhPelYwTJY7yX8SEpyGCbcW3bch7m1KlRboHQonbR7/YgziAjlD0toKmDpAAWIW7IAP5AQIIExyXEvVHkKMR5XaH3T9XSeMlGHCBxSp7GQZlU1k+puarc7mM=,iv:3o+AognfGLa0wznLcficoeaLKODJnkGsp77bZFBqKG8=,tag:+uKr7va3GYPNxt6cpQBwzg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
