ansible_become_pass: ENC[AES256_GCM,data:dNYOrBH0raiZ0g==,iv:3zhMojI+RRJYYcBOglYN1BOD3Y60sE7CIhYNbuvQ9eQ=,tag:63nEheCMtiZ3IkO+TTBXOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WU9kWk82QmtCS1NHYTNM
            ZjFDSjA3NWVvWTlweTVWb3BERmFTd3pCaEI4CmIycE9YKzR4c2xoTHY4L1F5ek1B
            OFB2eXFzUkNlNjlrMzJPNFVKdkxkazgKLS0tIGMyTzR2ekJyV2lka3dVSm16eXJ4
            ZlhsVzVpR2NsRGY1akN2alkwTGRTa28KwUXJyna7S3lcynsa93sBDQupR4W++ER1
            rFrJ/os7TguPUlXtf0D1u43OsFpcYZyxCn0DzAQaHH3hu+CVybSDYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:24:38Z"
    mac: ENC[AES256_GCM,data:QRLeLNOMxyMidISvNMV6gexJXCoLhQe9b0bqI1s3YZHCCY3tzoS49Vv6t5P3m5hte0RlzkwaZg46SP5898gGc1umz62rj9aoBN+FO97GoyWq4cFe86dE/0CeIEdntc5pYICS54lRgrXa4sufJ9OxzRarqCz6Gwo8zJLiVAWxr1M=,iv:ZkRr8pX5DdpktHohDdIA79qrfKWcErLTCwijQN4uLSc=,tag:xVyM06Mspgn6PXv2C0uHUA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
