ansible_become_pass: ENC[AES256_GCM,data:5evLmozN381Vbg==,iv:MxD4irnmTOlcka+dLTuTWYN4o7dNSIpUGRxoWXwSPDo=,tag:r5KOgPYgQhEjdXYW85y9Lg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OG03UzdscklPWXM5RkVv
            NFdOenpsNFpEUnpBek9DeU4razlDcG9YZ1d3Cm5LczlUOXEvMGNrM0tYWFFURmNU
            amhlckV2VUVUdXJrSGNHZkhEUlhFNk0KLS0tIEFjdzdlMTZuM1lueEZnNTFxUk5t
            b21pSlNHOUN0TUhoOW9lOTJWRFdod2MK560MdgwION4uueCquh4V5ffQjZ0N64km
            Wke4yJxhstPP24btlvWmG4/7VaNO1hPgY6GFx0Kbd1jJBdRd8VhGHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:24:39Z"
    mac: ENC[AES256_GCM,data:mUOHQ54yTKmUKTcisqwhlJSQUGzI61RR1DU7Hi9imye/Y6rsUSEGARUz8U6Q0RJwvFBHcI5hJ+UJlybVovUyENIpey37Rldo2mpnmsuTHD70nukq9NmTJdMxgiRwUn+0O9SvDdgoKTAb78ATb21SbD9X1lhpoWnMUrxMwbqFtZs=,iv:gYVBLpQ9brCKCG19zT6pHM+oITBrhjScG5GrUB1MVkg=,tag:7o9CguJyuNWTYvbjhrOt/A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
