ansible_become_pass: ENC[AES256_GCM,data:42kfOJUULbJMOw==,iv:tGTsKETO2CvRj3FA9372mV5kZojMDt5bpGVIyRgRKrI=,tag:DEwgVf+0NppYGXfDxW1abg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNzJ5NnoycHNBdm5JOVJy
            V3gvQ0d2NjYxVndpQ2lMV1lqYWI3VnVPU1RJCjNzbDA3QVpTS2Y0Y0Rza2VMTStC
            ekJYeUJodk9wWUU4U01rVHlMR3Q2WmsKLS0tIEE5U2g0T0d1eTZORWtySWx4a1pk
            WFNqSE9lVVdnOEF6N0E5bWxSREdTNlUK0GQiAeAxvItRsCorKZElhsgwxjlfPgl8
            1I63d2llpS/ogXIWtaRoTR70VpO/dMQVm9q0JbSVFQLoDNWo1nL/JA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:45:35Z"
    mac: ENC[AES256_GCM,data:5zTUwKXfr9+N2Ddmpmt1raliSQMA27ZdngNNSEb9wtZ+oPEP5C7cWpVuRfQkvy6EE57c+XKvWvmgSPIOdCjMrE+wTKcUNHhO8sNU5E3L4lMp7Ailht/F94cGMiuWtL6KZBhWILByQcMSPIQE9wa2WfkwC14t1Q9V7rvTwqCjaEk=,iv:gHzBD+RkEOuhkCV0Jm+jviregd87nrr99E0vTRM0Avg=,tag:Bd/bTTfInqpU9VoTyKflAA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
