ansible_become_pass: ENC[AES256_GCM,data:wi3WvOIRbtU/FQ==,iv:/2d0LonH1+mxRGAilEFnePHzdbf9CHi59nz4IuqB8js=,tag:ZZa+XW5HWiHBq39BS+hOaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMUxlSm53U3JqYjljV2l4
            M0xESG1XTFdINThmVjN2akdibzBqbjVWY1I4CmdQT0ZKV1YvamhDQ2hJQ012L0d5
            RGFhdXpRSXkvUGx1Q2pjS2Z6MllRTkEKLS0tIDdoOUJiTDhla29SczhuUVpERzJK
            aTFyOC9CNjZpTVNITWg4K1ZmcVBEdDAK3aTqcL2hZUS7/FRW1tsFL1MFU8tAG3bC
            5kXYH8noDYC/kTgR9jbbkelNkYa5r6WiHgINk6jH0YOSWqvn1dJQTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:45:36Z"
    mac: ENC[AES256_GCM,data:PwJsf0w/MZHOFC3GN2OefF+VWsg4UwHCw5MJD6Ue1mn7KAJyLOc1NWHaV2hJAvJzDaYWRkj34UnfkxwoI2Wg8vUW6+azf3JAiCbBcc3uytxE6p4pH5pMgbyI97rHozeOsB68w7uG9+h7jgxRNmWoZDp41oiD36evDU2BFhpCnz8=,iv:vi+zYk5EcVIioXOrnd3lrZAYd3mkhsqKNwvijH0fnbg=,tag:TyiqOPUofjp50lM2K9fQkw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
