---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ipmi-exporter
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        ype: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: prometheuscommunity/ipmi-exporter
              tag: v1.7.0
            args:
              - --config.file=/config/config.yml
              - --log.level=debug
            resources:
              requests:
                cpu: 5m
                memory: 10M
              limits:
                memory: 64M
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
    service:
      main:
        ports:
          http:
            port: 9290
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          #external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          hajimari.io/icon: video-input-antenna
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: configMap
        name: ipmi-exporter-configmap
        globalMounts:
          - path: /config/config.yml
            subPath: config.yml
            readOnly: true
