apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:29LHqaORFvoCxA==,iv:R91u5lCDXmZ0acwotX8DGbOUMMPhq+NUa0BEq7EBZak=,tag:2isdRxzk74rzZ6Hoz4yAZA==,type:str]
    admin-user: ENC[AES256_GCM,data:1HQ9oUw=,iv:8KkNrZHB9r8k0/lFuyrcFFeOpoWOJaEG5tXzDrSMoPA=,tag:V7xjncqrZG1MwvSFcxduug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUTQ3SVhabEk3MnpINUZm
            M0J1R2s1MjJvS2JnWExYaitEaHZoa3JOa2xJClVBSWdpNG9TZjdqNnJKaHA1Nlh2
            YjhYdWlpdTFGeGEyWnpNMmpNNVAwOXcKLS0tIDdoN2VLZmYwcW5pUExYSllNR2Zm
            N09EVkFJQXBCNmczTlk3Y1dXN3JwRW8KsrLbygR8hmrXzIPIIpdjrozC5SkwbHf6
            DLfCkTl8qcGkWF6E3+LzH4RF7md+G6rQrzzUG7fHx7cWabZoisoTdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:25:29Z"
    mac: ENC[AES256_GCM,data:vuLF/9LIl4GyB2G9YWx70njOyh2IZLJQkicyPtP9GxmQc88+/QvHONUjbgBwDgC5i/gfKhtu9w3OYy590eNm27i+w1OopAJu0ca1FZbZtllZmvzWD2Zm+QmKrqJ9hDvI0ANZqN50t0KLpL7nEmlprIfqvD1YQlh3kGbVZtrRj44=,iv:HJtZNsxx4g7HuNBCfO/dGY9346893c4JzjzOfSgyBsw=,tag:nL/0HNP0i6rbSW95TDwjgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
