apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ZLNBCieTOyqkKAp4nLM396hORzbJr4R4,iv:xjh4M45UsUWYA7dDPHMaxtDXocq8EZutIyKKzW3/rBE=,tag:aa6rrqXLawgo0DbgHzGTMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzK3BIcHVTc0cyVmpBczRW
            enpYbkNOa0ZpVWRyeFp4Q3ltUTVrd3p5VDJnClM5UnZSR2lZMDlnUUVCME1EcHlu
            eWJ3VWRWYVMzdUlqMWJMam5MKzVKaDAKLS0tIGtGYi9jNkR6OE91ZDh0cTB3RmpO
            OThsSnJKREJRd3p4N09hRnAyTnNaYkUKmWXQoEkSG4rpYwHHVZ63ea+5P94nfvm0
            CCYWBE+vgg7Uf0fjOD+xYz+0rjuMZRToaLhqA8O/XZ8IoREAyr4saw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:46:24Z"
    mac: ENC[AES256_GCM,data:uHXnDQctnm9a4a1bwWc9YSAPwya6aXCETguC8dtHeeRTHfIyKE0t8nu1Gt5FU8CQfHTyfEW/iJh6oZCw9c1rfTgX6ywibUyq9/1Mm3RQsMTkZ7br4RMd+R1yWbS3qNUS/hqeas5jN9XBP2LAbMHJElwq+yFVKwE/Adi/8F/krjU=,iv:3YcK8z1eSmF9O1+rmlJ3ZfiZMtfyDl9IpUVxyoK5haU=,tag:dTTG5p3vIm01lQGoJHrhUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
