apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:l+uTJ1olaI/fZrjBLCAyMcyq7asZs8B3,iv:7ulJ6BjT9QSrrfaKHfLwxd1G9w+j6dOmyRxdqdnNc14=,tag:xamMtZ7PZQ6yC9mlyHHfQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRldkZUFWUTdGS1I1UUNj
            aUF4NElITlJuZmpqN3lRdHpOU2lDRXcvUEJFCjl3L1RTa214TkZkeFJrT05uMkM3
            d3RvQU53ZWZrbFg0QStsR1FEdVY4eXMKLS0tIHQ5ZjFnSnJlWGNBMUc1VHVZSkRi
            Rlo0VzI2Q2tUR2hlZmJYVnpPYzFsd28KIfDA60yb0m21M03jdizZdkZg4Rmqd3rQ
            Acv5UzrVVRKUDM5F0V55JTp1lSqKRkY0etsPyQ5/5GobIksVkFfTvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T19:07:12Z"
    mac: ENC[AES256_GCM,data:f9+bRtqtwT5Xb3oaVqdHmKOqF4RWeDJ3VwVKfIRLCte+F50WmENWrE9IWUx7FWJyRjoVZqWy7PKBy22TewBJAcNbpMHMCNKeALy7nhJoDSZfH3aMTClpg3h8/piQkr/zuUCqqgwhsHgJodzKnA20EeKA8Blj0RU7015qfOQe25c=,iv:gJ4lNs+uxTOySLeBxSC+IffBhGWvW/lzrPIbuZLw4uU=,tag:WG9q/aCpUtlt3Exm1s4i8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
