apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:jov/5jjcr8SajY2u00tc0q6LpH+Kwzth,iv:ogi7XUXKirO0aDQ4vloHzQleLlm4c9A8dYAYQrkyGNM=,tag:ncBSAhuy+oi+WPcy31CQUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dFFERVUzWmdKY3RGZi96
            cEtPSk5QU2N0d2tsWWRHWTYwOHRIMlk0S1FVCkRFaEVLM1FubkJjanJEc3d4cXp1
            RHJmRFc2S1YwVHYyRTNLYjFDdGE2c1kKLS0tIEhmRWNoakxkWGJZS2lyYVJCc282
            SEFEaFBkNnFUeUlSejJnK0NvRExDMVkKouo8KSp18xX0UaptNWBvgFQ1VZ1XsKFH
            xfULX5cN/C4VBoYns9wCH4TuExhm+G1BhhcnRlqj1WNDqVXLFCBN4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:25:26Z"
    mac: ENC[AES256_GCM,data:L2jJpo62xsTy8NQ8EVAd4c+8W6IDDVTr2hUViV8nwqYdRZGFV2adt2uMNoxTTrencxiJLwDsMeQf35GYAGhA9lXKr31KH1tXnaZXEdKrZ0NrRouktltESasn4B/RZHhjwvLlW5HNyy9Kpz9ExF7vKrA+TYt0Y3rCg8+6VZa2fk4=,iv:kGwk4Bp3YEOsRnCIZ6LGAReDPfFCaH8NL3OsI2vRPkM=,tag:r1o1qdCpza2UtoKH3aKKVg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
