---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio
provisioner: nfs
parameters:
  archiveOnDelete: "false"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio
spec:
  storageClassName: minio
  capacity:
    storage: 1Mi # Size does not matter ...twss
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: truenas.calzone.zone
    path: /mnt/hdd-pool/s3
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - noatime
    - rsize=131072
    - wsize=131072
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: minio
  resources:
    requests:
      storage: 1Mi # Size does not matter ...twss
