# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:XAmNajm8KIMzwMruaIuw/BFCe8upRdcEXBcANdK/6vw=,iv:a1l8U1djWl8A2QKh3Na4vs81dhmlJeM08sXGxZ/Y1Fw=,tag:qKHmDb5tpOugzbNw+gSfbQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zhs8q2mkfm6a8pr6qlkklcgjkqzunluud63kr2z8vswk0v5u93esp4kj8e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNUtHV2hLLzNhOGp3N1Zk
        RUM3MFNtVXVUaCtGbnNDL2xyaTFiYVpCL204ClRzdnBUNDMwS0RjK2hQWjg5SXk0
        aVI3R0hxUjQxTXgxS2ZRQWk5VnR0YmsKLS0tIEZCSVUwMVZ3My92Qzd5NWMzRDdT
        Rkl5eWZsKzNoSFA3cEpvTFhMa3g0cU0KKEEkRr4FlFQ4L9zwqs7yuQIxtP+40ht7
        uXPL0817WftPUeDS+H6sS034d0cTQAMzwNEV4ZNUDwPd93qe2rF2JA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T03:15:31Z"
  mac: ENC[AES256_GCM,data:XzLydze1PWnHLC+9kmgD7Ds+sUJ8qEOTnUlzhXW8a14+Oe2hC6vyQV5ba2OP8itfM6zcfP8EoVEQv4IcSPnl29EBeIm3OxrbovoUlqptB0hvuTerWRf5ho+HSAcAdMKt01kKD1OJ/4l3fpPb/pgaOrvT0A/7UbXcwa+cYwg9tQM=,iv:ynBeM0eXH0y9YMawBpO17IboGQKslbX2gYtr9b0gLPI=,tag:etCLh9H62/vzID/9mLTjeg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
