# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:jsDZhKnmn+6tGlf6Y+6LUDh65lX14Xlcdtm9I3pyuS4=,iv:B4wH5aSe65YX78U6UY2NvWFE6SHL2dvFyckxzYaghJE=,tag:PpIcTBTfTN8AVzjgBRu7Ag==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zhs8q2mkfm6a8pr6qlkklcgjkqzunluud63kr2z8vswk0v5u93esp4kj8e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacjgzTCtCdWluVWZYdVlC
        cDhOSWVZK2gzNHFlU1B3K3p4aktNQU9mdjF3CjRYU2pndmY1aGdCWW5zdzQwbnUv
        aXI4L0dNQ0tNMEI1SWNzUzJOUWV6WTAKLS0tIHUrLzJPMU0xNmFBWEdYTXpPcFo2
        RGRpK3BXVkVLbzdab3E1SzJPTGdtVjQKd6R5VQIY/nioVfAuYod9CtN2UHF5sBR0
        oa9g5WOZBOM1AIpAF5hYaqCoM4KsBfXed0Kpji0CymREZ3xSpscQAw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T04:27:29Z"
  mac: ENC[AES256_GCM,data:mXejFHwpPz9ZVF/IN8BPe4R1ICabI7jqA1ETT4DRqF9jf9zUwxmGAOU2fEIb9nv0U6XXWwODPK6jUx7XecnPkEnDH4YwcfPDv2xKZsJGat8TgBICaU7u7UsCdEu0U3TTy7ha38B8YTt2DRDCmtHd2Yyg93VpcTRlxwJLcLlH81M=,iv:octbYFCPI9AIoJ9nrk6UJiBdlnRJUPJxu5TVSMKSxNg=,tag:jto8PfWy+SEEDUI6NZZs9A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
