# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:jID1lYXPi2Pe/EuEcQlDlEBMBl07jrw9XKlryIlHxW0=,iv:9eAbaUdmPDUSfKms1aC8bDObMxfMyG3+yI/VaTTu6mU=,tag:1OtfMEtMIlQgQmeb+wo8hQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zhs8q2mkfm6a8pr6qlkklcgjkqzunluud63kr2z8vswk0v5u93esp4kj8e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NnhsN1RzNE1aZ2NIZ1R3
        SlJtZ0I2Vmx5T3N0WFdrQlpjamJ2SjFtOGhJCmcyeG5rRndscVZCTUhKV3ZtM094
        WmdFd1VZa1I1N09ORWcrS0NUWW5pNnMKLS0tIEFsd3JIRzlhTEpZWUQvdkZENUYz
        Z09RdzlGN3dkQnB0YVZ0enQwUmdTSGsKHpAykL3HTVx9YHqeGoNXAta+9Fhlw29Y
        WIQanX+9nq5lMbiWQRzj1arYBVWoYxpQZ4ZwVtRRfC5+329T0By71w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T03:49:16Z"
  mac: ENC[AES256_GCM,data:URZSiIenmNfMg/CohmBkQqWUQWqNl0DBE1py0jXb31G/jWlih11BcLCVL4ZtaY7f+KJxjNFq4rkeFcgzMbsw6QrvadX0NjVganNkiR9GTHfdS+b8RZ8bYIL2BVWSqQzu3Njr/kxc++kEObcl9IbCsdk67P6xjfEIdXogeFXXgEI=,iv:YJs+IhmHATpw5GvRxC2nCOMUZSyoXMwL61wa/BQHz1Y=,tag:cA15sWmKC/9kurf4jGacVw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
