apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:5PtvQY5kLxi5aA==,iv:kl/MWgOEviXM0gb7NWWje+yEguV6EsbAUlBVb4YY7VE=,tag:KE2MOaylziiaJCyz5p6l6g==,type:str]
    admin-user: ENC[AES256_GCM,data:yNhN8Dc=,iv:JclDbVnxFnlxmN9cL4U2OXhS/oueqpPtMBBZ7eBymeU=,tag:Pq59T4wEm/a7fIUVtfImZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKOSs3b3htWVpyUk1td0NO
            MnRWSnY0Q2srNnJiN1pDRGd5QW10RkZJa1RZClBnRjByRjRQM2pmU3RNbUw5TzNt
            SW4yb29UMkQ0T3Ntb1k1VFN5T0ZoeWsKLS0tIFNmL1RNdDBNSGU2Y1BhTVpTQVha
            NVhKb3NPUTFJZFU3djF4NFNRVlg4SG8Kc+VV35S4Jf8GqwfmaGwUinbYmVaqO/J3
            mKmqCBJe8s/e0s1DJWh1wnJQYlXc+f8k3RddaIY81QcKjFNfaploFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:46:27Z"
    mac: ENC[AES256_GCM,data:3sw+vsJgGhhoCKr8Z6CUgraIkk0w8/VnCO/Ol6czI0pGwXQ63+O36ggOu2P1pKnTlzfqOLnwKl04NOXgI/8Cb91+MlXFqbZMT7VGe1MUC5/+7girNI5ISLNIzLh8zO+BWJm22MfWEVa+UyXtNAjgeClD3jQpTh/bpwGUSWpsXx8=,iv:sMbGxNorLsMQN2PdycZiHEL22ExbfF0crgrG/ywn+Ds=,tag:SU+R7N4DjseFOwvm0/EKIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
