---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name authentik-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # Authentik
        AUTHENTIK_BOOTSTRAP_EMAIL: '{{ .AUTHENTIK_EMAIL }}'
        AUTHENTIK_BOOTSTRAP_PASSWORD: '{{ .AUTHENTIK_PASSWORD }}'
        AUTHENTIK_BOOTSTRAP_TOKEN: '{{ .AUTHENTIK_TOKEN }}'
        AUTHENTIK_SECRET_KEY: '{{ .AUTHENTIK_SECRET_KEY }}'
        AUTHENTIK_REDIS__DB: "1"

        AUTHENTIK_POSTGRESQL__NAME: &dbName authentik
        AUTHENTIK_POSTGRESQL__HOST: &dbHost postgres-rw.database.svc.cluster.local
        AUTHENTIK_POSTGRESQL__USER: &dbUser '{{ .POSTGRES_USER }}'
        AUTHENTIK_POSTGRESQL__PASSWORD: &dbPass '{{ .POSTGRES_PASS }}'
        AUTHENTIK_POSTGRESQL__USE_PGBOUNCER: 'true'
        AUTHENTIK_POSTGRESQL__SSLMODE: 'require'
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
  - extract:
      key: authentik
  - extract:
      key: cloudnative-pg
