apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:GjK2vVobsPkXQ7o5gvtIBeYus5rK2v2+x/HQNmay+JGcnnHYWDL9HA==,iv:f0TcHjAFlKYLwLsrqZdlNdw6Rp7riDW3dP19UqbbcQM=,tag:eDf4bShsYDQn21FhgD+ZAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RWpDQTJmcnVldC9YWlBw
            MUtka3RUVkR1NzhzYmsveERiQ3ovRnQ4U1VnCklVeEk2azVpcDdQcDIyMStvZHVJ
            REErRjlKSjJ3UldKUlRHMmp3MWxBME0KLS0tIFRaM3llQTFmVlEvaHNYVUFZRnRu
            RjBxQmFvdXM4YkE4N3UwZmlONWxaNTQKQ7ycesdnkSjOeEoDrxqjjfnNHHzFDy0X
            qjVLgbiT74k6GnCOllPM/JhU6FNzYaAgiemF7N6e7u/Qi2fG0lHwdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:25:27Z"
    mac: ENC[AES256_GCM,data:5eHK+tqneD4ACuY/GeGsZOrpIC21IDYFeWjOevqFyS1StvpKDXbYEX2Nsnk+jiGCP04II7xPOJ03qCWDkfCp8xi+Tq0JCnnHpaTxVmv/0b4oFp0HkmT5m4BFKRnLnZHNkbzjHMdaE/DhsWL16G5U7EsL9V2Nf+GLfhVpfmUl1+M=,iv:PX03O6QVycXGwqrdOrSGkFTuW4Dn5qfMk5ilLQa1kU4=,tag:qWhTQK8YnKDZ2c4gESIp1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
