apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:g9RDDFFWyY1e3Ess6um+HqhEAxJ+fKOh8fCFVtFTgh0JTHawHe5wvQ==,iv:HDtbK1AenH031jbo4pqwXloPZs/rv8mXQCC0vXJqT2Y=,tag:nTdtQa+5i+gj5t+XzALXgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcjh4Q2VCNDhKVVZISGhl
            ek1XYnFvdUpIMzA3Tlg4bG1TOTNKSkpEaTJNCjlDZURjb3lueHphTjRLdi85Ulpm
            SGx4NEtFMG8vTTJTdGZ5QmZPdm1oMWcKLS0tIFp5dVlmRHRQSG10d1lxd2VEYnNi
            UHg2cjUremlnY3FPcUYvbE5VUm9vckUKY0L7g3CyYgqwRKaHEpv0AV6lkbaco88p
            Y8CIP8iZvPC5Homb+w07wCniIIRGZP7YeOsFJnv5dofleL3MXALoUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:46:25Z"
    mac: ENC[AES256_GCM,data:IYegtUVpLgubIAYK125JYWsbWhp00tWuctKroAoQPkrYAqqUpaiRJB61ssK75bho3Lox1xdkLKFJVmTygaPdBpW2Cgo2UtW5iPXRfhW31ovHyFKyxEagfc7OffMPtxS8YIuDROhH+nmUzaXRgdl1gWCCpzpoB8PF+6/mbnu2BF4=,iv:y5dBWLtLvl5se85VL9H25D2+Yee9sSXuIlofoIdODYI=,tag:5rN5wj5AG8wzVChy+nCIjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
