apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:1sFDcTWSf73vmXDRqmoSDDVsQ7LFj2O+mhKFzE7N+w6mVv/oU2ZFQQ==,iv:BeQ6CFOBeDbtRz6u5LepmW2j70NZKbEcUjXw+Wtsqdc=,tag:wNT7HrLQXg7k63R+U8AjMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMzFlcU1JclM0VWd0aHVJ
            dUNsaml3V0t6eG9Jdjc4aGJMbEtjcForWWs4Ck1ZZzNPUzgwRWtpWmJLa3ppZ1lt
            VW1mZFgzdXVHcTVkc2NxL1AxZXE0UFUKLS0tIG9FR2t1VTlSQmtsa0RhOTlXWWw5
            NVorMmEvcW5WbCt6M3FUREZOMTM5MTgKPRRz/N6Xbe9aafl/KYJqA93lBwumSm2w
            +IYjmUiae+xznmzpFzLE28LHNONgwH3+SCaKF4qcHyWl1jWyAkZyRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T19:07:13Z"
    mac: ENC[AES256_GCM,data:+84I5t7yWqLVW6Dwijn+IYpNC3J0MI7mSGPx+ewQsCkdUXdWnRysgdsf/w21HBeXMWw7QMEu5MvNAY9mrWQmippjcotB8Z54gqCuRYD4OVmr1jMdLX1x81IPfgNoin29kjF2+WBt3HT1QggE8Y3d68GtCP4eHUIfYwrx8SqlgC0=,iv:2YKfgBNWqWysSnOAHVIyvBt5j4JG8ppl4u8VZFA8M0Y=,tag:PBsPJG1j5XhrsyB9SBAigw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
