apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:jCOfle2m13g4lC9aKFTiLifUJnzDRm2CKJ2nYgvJBkVTVYeAjcsv7A==,iv:R9qCYGv0c/iv6jFwVanc1nWAsn3iG/+TsGqZ8rlIcLQ=,tag:nbnVz59IU5ZtEOkMCVSWPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UnppdTRLYURxSmVja2Zh
            aDkxU1IydmdZQmdUa1lHajkyQndxdFhnb25vCmdDOVBpeG9uK2RWMktoRkFXWDF2
            OUQ5MVhRWjdWc2w1cjFBRHB0UzUva3cKLS0tIDEvM0VEZm1kTjM3dG5IY2c2ejU1
            S0pqbG45aG1QQk1OUE9PNjJPL2tocTAKKtPk0vKUfj7QPbY9+R5WeDVqETVhJ3gS
            LbUeLAFv12bt+eR3zcU1+dazQLxRpRVGunIZnOZuIQHamXy571EANQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:46:24Z"
    mac: ENC[AES256_GCM,data:LjRd0XvJyxJ5lR6a+UkF9oDtQrzZRIc5pmqHO0y13JgQsXvpgYbwm+/eiqErErUf1JyVhxA9PeANGbTIth5kLS6jEiy5yNXzQarxW89HqyvD0+ddSERy33jyFu4NLbrJzUYv7hKaF7dQLZXgCz5pIJWNcbmPX3fnG4dRtroo2vo=,iv:p6lr0nyjI+rX5sNruu94Yzmpxlubd5P5zQYYFleir7o=,tag:HsA1UxqdKg3DIGIGwB3izQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
