apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:0TLJ+PIkD9QgX9toUNNK1b9T+ulIp4dpsf/zvnmuwSsJS2sgZWVYkg==,iv:uWUM/S3rDas/TsiYUaJm8S4y6Ys3zIhHVNGcy1NZKLE=,tag:TxxfKyBsQfoJfYMYNEBP/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5QXB0b0YrRVgxUElpdTBx
            MWhzeVFYTWFZTDFaM00vM3crQnU3NTlHK1h3CkQrMUc3eW94dmhqSi9GcjZKYkNy
            WnI3elVNU1QzUVYwVHZBVW0vdUxQdFUKLS0tIFdMUGJ2YlRLNmU1R2FyZ0tWZ2Nn
            bm16dVVUc0EvRE1WaHQ1ZkFRVi9EUWMK7oFUuXCdBv5JuGT+bNtU4Fl5Wmjrqtp1
            36JhYwxgr/YLV3eDXitI+ItQIJdVohWldlNCoWuFhVZ9its+7gTuQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T19:07:12Z"
    mac: ENC[AES256_GCM,data://X5b9cwcwPBeJc8ecFiQhwudSX5HHX//uE5lXZ1djiaMHkm8Mz442aJaL052PYoTd7xUSPN0UE3b84caW7okIg9uNF9Exj9gVisHZncZv3Ja8zH2cKzJe2GC/I9OI4guT5K+nufPHBCP8ICJfQrV7dt7LogmRaRXZUcRq/ozik=,iv:ONY6W2rVKwHy6TQT/jqdBHsi/t9rreqqfU+eXsIV5+Y=,tag:D5Yl6E1wPmxhhAkPswslhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
