apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:gxadcigueuuBEUyr7+qVwGG5330zN1CIZxAK79PjP6WUi/9/kXhkCw==,iv:uE0f62yk5pVj/wOxKGJ0FWK9mniooo7kUWFjllwgPto=,tag:82U9NJ81n+pzb1JPw3Gs+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvczUxZnFKcFNsZXZ0SzRv
            aFhDYW5HOXUxSWVoNGVVaW03V3VzcGsxbTNnCm1RMThMdHloeUFGSSs0MWp5b2Nm
            OSt1cDg1V0dBaDZsQ2ZJQjBDWGQ1UVEKLS0tIG9TMnRpMWVIVjNXeFAxWVB5eUZQ
            MWk2YU03eStxLy9XWjRZM0s4WEtNNncKyuO1dklRT9GCgDFBF0SXQ2Z0TusVZw3N
            SOP/QGB+BZgwT92euGIZ6/KEWHMg9mQH9QQm06Ll2nllvp3iAlaWNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:25:27Z"
    mac: ENC[AES256_GCM,data:JsJBeUaTocQFkZ6ya3YirQrlxvHcjU9JGIceAQdT01p/R+HsBtX9T0nmj7wWcu1vEB5W88DgKPef/IOadMCqOTIJmaDKJHkmoOLT2C38LTnzLhZtoEqE7Q1nzYEBIuTtR6UZMos5tS74fXVFgwFtrSdRemXOKiA85J4krLP3Fh4=,iv:SliOpDWYBQskYpK/rGUhPejTLJvOe0GGfcXaIrrbyfA=,tag:H/aB7YKSYQ9eHgN/PB2tCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
