---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./media-pvc.yaml
  - ./sabnzbd/ks.yaml
  #- ./immich/ks.yaml
  - ./overseerr/ks.yaml
  - ./radarr/ks.yaml
  - ./minio/ks.yaml
  - ./recyclarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./tautulli/ks.yaml
