---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ring-mqtt
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ring-mqtt-configmap
    template:
      templateFrom:
        - configMap:
            name: ring-mqtt-configmap-tpl
            items:
              - key: config.json
  dataFrom:
    - extract:
        key: ring-mqtt
    - extract:
        key: mosquitto
