---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.2.0/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: scrypted
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: storage
  values:
    defaultPodOptions:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
    controllers:
      scrypted:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/koush/scrypted
              tag: 20-jammy-full.s6-v0.99.0
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 1Gi
    service:
      app:
        controller: scrypted
        ports:
          http:
            port: 11080
      video:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 192.168.99.107
        controller: scrypted
        ports:
          camera1:
            port: 34135
          camera2:
            port: 34136
          camera3:
            port: 34137
          camera4:
            port: 34138
    ingress:
      app:
        enabled: true
        className: internal
        hosts:
          - host: &host scrypted.calzone.zone
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts: [*host]
    persistence:
      data:
        enabled: true
        existingClaim: scrypted
        globalMounts:
          - path: /server/volume

