apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:KXsjeLH7HTwmUgL1,iv:433c6VfbFfEOMSPEmVSh0NpgO3KaPHwiifJ26l7Ft+Y=,tag:QUfgi3Sq8GSbbu2a55+Jng==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zhs8q2mkfm6a8pr6qlkklcgjkqzunluud63kr2z8vswk0v5u93esp4kj8e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBd2dMT010UWE5TzIrcGx3
        WmQ5L3FXbUdySmo1Z0NMMlBucW9XMmc2MWdFCnFKOGN2SGlWVEd3cDRPRlhQMllD
        OWVadFAwREllT1ZjL2VZUHAyMkVEK2MKLS0tIGdKbWRkTjFnYktuQ2xaclRZMVUx
        Sm9BckxYT0VRV3VPaC8wenNIeGNCd3cK+mSM5PAS4Xk4bvgTGX165U88qcLOLDPM
        92lOtryMYGNoHzq2Kt4ZgEgHsvqXu/xiKL10QdSOSYIOvzYeIGIFWw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T03:15:31Z"
  mac: ENC[AES256_GCM,data:d8BOENK2pABFJUKkmVWkZUHr0FqaOjtHUpYOMuOgNMtgF2EKwcd8hSVfufh80SBYazqL1cKRBPsCMRt+bL8A9eqr8ncA0JC3FG4ZQWW1jMh6JlCxd+33FAtngfo/oboLJGYVy3mpsUyfIdQ37H0+F7vOdhGujdNFOZLyAJufktk=,iv:Zmosk947l8lh7XNsZ2EJQudPAczTGvopcwo6tL5M7qs=,tag:Hi8Ixu8IGLxRTcHuRkkz1w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
