apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:qQirPWSTtZZl7myA,iv:2KJDBVvUpIvjrRa/jxe0fDoQuqsi/O9HOsenDLms0Jc=,tag:BdYhUwgB1wR9op70k4qpVQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zhs8q2mkfm6a8pr6qlkklcgjkqzunluud63kr2z8vswk0v5u93esp4kj8e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVUdSUTNaeHpSaE9tSzAv
        eWNBRXJPeFhYMFBBcHNiTExGYk1lZmE4QlFNCkw1SGltM0hJVUZiRm5uTUhWZnRl
        OTRZWElOTDRxNnhHT2pSLzRjQWFSdFkKLS0tIFFlMDZidGVWbUhWV2dzQjRud1Jv
        Z3FhcTV2T1NNSlp0M05wSUZpdHkxTTAKB8+w+lE/kZYFEl+Sg61+wDDEczXj36cl
        E5dmlCsC67wx4nB8KO5EkTxN80erue8KHZMmYPeGPdY0bETpUSbeRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T04:27:29Z"
  mac: ENC[AES256_GCM,data:+k31zoQTDuIB9CWzUKZaMZDgPP5PBu6VKP9R7IH77ps5W/rX+/y5Ei3mN3+aXq0QjCJgCCiq6JMOxLhxSv5D1jfHSXN+7lXif6EJPElhseopqmuwx2QytRSGBV3XiPzFXWYayJeu+o+ulVa7iy+GDOxPqgOF6m5yWq4lsi50Z9Y=,iv:YgGpcaIRF+YFXo1fY/jlrOGtr4bVIB8qKL7MIXAqtZU=,tag:7nG9ktKVIBa4wUblJSE6cg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
