apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:AfF2rLBr3fB6u7Ps,iv:SHXtzpSkKGchbxiDVWAxvLXeDs5NW226o3Uw1ymYQyo=,tag:a0/p4HVC8bDQ8C9ZuqAXQg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zhs8q2mkfm6a8pr6qlkklcgjkqzunluud63kr2z8vswk0v5u93esp4kj8e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUkhabmd0bWFqblp1djZo
        N2ZNdVRZMGF4Z3VwaEx1QmgxSTZuaDlrbTJBCmN4aDhNRFNqQ3pMN2ZCYWxXVE9p
        OUQxN1NCUXRMQVBFNzdpNXJmcTZZeE0KLS0tIEU0U3ArM1BDUlR0SnZnUncybGJO
        bzh4TllNRTZMUEFHcFVzK3FRTXBjdlEKXGe9+4k5PH2Fe4izevcufZPYDl32k3TZ
        K2GqHxrKbm1hNHXpYDnI7PDGmeTRKpAkmK9DjiGnWnUXp2CHeTmULg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T03:49:16Z"
  mac: ENC[AES256_GCM,data:O5ROR85ZJ6U1X5PeGapRehu3VIJK9exkqb+W1+C5dLQhekZp1rbmtEThpAaapjcOHirAWPzRdzdMPeJGq7lIfb3cZzumQwcUkxp769xXds/nxuiUM0ft2KBsQs0SqO3N/b/3iwL4dYdkCYLVNP8nmGaafc0e7bxcz1mbu1A3+mc=,iv:nZc2duLMgZN6B0TG+zSmMRLzBiBndOz0NEUBwPfpfCU=,tag:ID04iQaPS4wNPtpripwhkg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
