apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:LRO9RTmDAIx/9tYn9avCOpAzS835TjyiwFQ0mNctCCldh8Yzhqq7QmMxs8ZTc9VjKtixaD/WaPfljlSYq1m74EIhx5lUxAQFUWg=,iv:bj0orcKRH012TgKOb/Ux/bVJihNyadZ7toF75YSzGRs=,tag:cu/HFo/2dgxfSm+JBNuS2w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zhs8q2mkfm6a8pr6qlkklcgjkqzunluud63kr2z8vswk0v5u93esp4kj8e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmby9xdFFPRUg4dktGMXVB
        ZmNuNTVYTjlGV1N3RzJHaXZsQ29WWDhSR3g4CndSaWJZN0t2cXdWSzhCNEJMSzlh
        MmRLMmE5bU0wM002WXViTUtjc1ZRWjAKLS0tIHZHSElmTmxqdGdrZ3JDbVNUNnNM
        bUk5c2lJbWs1REVlU0gxaDhqUEdEMmsKmVWP2cOfqKdGSXtLt5Ls0ajLshvBdDoi
        aVziha0wc1c8czONkAacsznQWb8fbx7imuyftpkaJNZ5WUT9Vtxtvw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T04:27:29Z"
  mac: ENC[AES256_GCM,data:6JoHwTxZUpSRrAwMsWxXX4wTg+hTpbtcZ+caAsN0VVHrZPBdvfi3fRLpla5BUNne1+6Igx1grv3YTZHmK3faZHQU0zln1ZQGIhSZMGfDfyzPOK2Dw85dm298AoXODUrPx3tesw8Vm68y1Nju3jeQk4Dmo6BD+/vS2wCSr8CdM3s=,iv:SU8YQI9HotHL5/g4gMYRp2pzqMBWtgYPPjYu9Lmqsbk=,tag:Bvl9tgoQ8yA1UPoFikBdwg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
