apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:he/jPv19jR9n9rlv/wM1eQffUpDyHurMQicN67A5lMGYUL3u5lFvDYgrtp8uMwSRjRv/CqNWRaVJru43UavHb2dW5tIYxfxBgNk=,iv:Z9u9xLtqXJZmV8KfMQ707LnM3OoXpgq6iGZ/dRm65/I=,tag:KlVs3sfxQprEa0pcODT2EA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zhs8q2mkfm6a8pr6qlkklcgjkqzunluud63kr2z8vswk0v5u93esp4kj8e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOXVkd0pJMmFGZmdDSmov
        Tlg2ZVV3WWcyYkFiYmJ6a2p5KzN2ZjAwZERnCmE1d2xuSDFmckMwclBOckhEaGtM
        ODlmQ0FybnZCaEdKL3VIWEQ2c2dlVGMKLS0tIGJLbHNpZVVhNFdYdFF4WGhERTlz
        SnNlbjBvbTVGSGJ0d2RKZE1UdFBSNEEKq9yOTYwoy9plib7DcGUkTSstztaM5stW
        tJCp5t6jrAEF9eTtEzHkGlO/xn1e+POdYhVv2tRKUgpoVeHHZjWlvg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T03:49:16Z"
  mac: ENC[AES256_GCM,data:h64JYPzYBL2uzWu36j50UANdbOBEgq3I5G9+UB8gFo5iJN246TEAho1UMTy5+nXFb4WZ8hDpg43h36MpXT1ZPjAuoBxURhRjQMmqieEEF1vkOBHe0fecIpnug/FUbr6y8bs77WhNC+QskDZmmqxMywIhr3bxDiHQBEcF/yu2XQc=,iv:0fCIHmtFmFTK+u7nPYQ5O8etSU3mpbNEZM3S3mE2WBg=,tag:Qohzp28CxA7AjvNYFxP6DA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
