# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:0JkaNc/Zb2ne4TdOf9U1j3zMWRTGVe8UFyCGUIFlK8GuxgHERdKjjA==,iv:JclfGuvdEzdpyR6IugAyjncKGnAo0rmxrzKSPqoGrXk=,tag:+V0aaKGOe8iws669If7SZg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zhs8q2mkfm6a8pr6qlkklcgjkqzunluud63kr2z8vswk0v5u93esp4kj8e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRHUyRU5icEJtV29IdTF3
        eXozZm5KcWx5TkwwaWtsTjRxQnFuajJwREZrCkUvV2hrc3FpcFlBL200Y1VIZDRU
        azlIVlZxN0wwK1RpNjdGTFlpdEEyQmMKLS0tIE56MUJEZXhFT25ESnBCOFlUWlg0
        NjJTWEYzM1NKeElVSWlnbisrWlYreFkK5GkuC9fivMpHPC1rYG88yx8kf3wpXDml
        0TT2YsAeSg/g6hl996JH1SiG3sDHYS7JSdIXlkUcgz2hbc7lhKPrUA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T04:27:29Z"
  mac: ENC[AES256_GCM,data:SA/jn1u3uCiTRGFkGbIV5LtjAx6faPLHIzHLBwuEhzmggtUDQfYRnsxE6OUGk08NwNj2gVtBIxJ4VwfRw/eHwLkn6OxApScY6JEHoW2S4qra2hjDqTzcFRI+q3+i8acyuQvgoNAv2KHLDXouVngNna9b6h26ntp6vh0IHBHedIs=,iv:weNKN1HPHsCHmSYdgR9ffCvVa1IKRmmCCNYIzYAi9BQ=,tag:+JCF+Rpk3M8NL5r6fqolJw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
