# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:w4f4xrJs9c2qonUCrq6vLOlY8cXCKd/7LpelI1OQsJt/6nWcPfExvA==,iv:JtxEkXzC0Zvl0ORFa+PtZ0gGIJsx1qyWWEQIBQD2fSI=,tag:PSP/DhZKL9vg4cfoc0SWnQ==,type:str]
sops:
  age:
    - recipient: age1xxx56w9n96tq8a4fdyf8qjvecxxdxa6wfkdrcmclkwtlmf9uepzsjk8kxm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MjYyV2dKM3N2eHZwc25G
        WVllK3MydVVrY2FPNWJjVEEreHZnT2tyNWxrCkY0SkVlV3l6aG15S2dHVDV0Unpj
        TTk2TVp0MmY2andZbDdJeEluejBvT28KLS0tIENIOWhFS3RveFlXZTBtYzlzVzlk
        UGdCOHJ5Rk5SNlVxdVc5Q3dMZisxWmMKB2K6C6VPD6VAHPUMdCRSCQTXdb7x7Izs
        DAfNMFto/mHqA3bS1jQyNYOwqns4AA9E5nkqUsKBST8wx3sa1Apdcw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-30T21:40:14Z"
  mac: ENC[AES256_GCM,data:kgOidJ1LREAsM+JbTVkY35BQpIR8yLmaoDy62Ybn+7voeRT9jvYy0RXXCDNj1H3iLjmTCM67x1SBS5RF96OKCCWerJ7yEzW+W74pbJMmcDzhn4hOiWIjxNApBv90YggZYsySikmLKOkVg+Njmu67XEan82lXFRjlF3NSp2lTESg=,iv:iROxsjpmeU2yfTON7JewIJzZC+TQcXNzjT/JgAT2wG8=,tag:Dr/DeIujvFye1Xt15XrB1g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
