# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:vhsfFsX68ir4ACYzgPzJ3qNW5NRxfBNpuS6b3DdOJ3SNrPMRquqz6A==,iv:N3GHnNDzQi5RQwvLYzZrLNvr5YIhjhFPtBA+bg3FBUc=,tag:OyWJrZU3KisR9DUVPIwWWA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zhs8q2mkfm6a8pr6qlkklcgjkqzunluud63kr2z8vswk0v5u93esp4kj8e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSFE4ZnNHZVNNK2NSZWJF
        MWJ4K1RYYTZEZzhnaE5FbDlWcDR2ZUJsdmdrCmxHUU9tbXlYa0d0MjVuaU9nWk1R
        Z2JWTWJ0clZvNnpoTVhWVkZEMmFFZ3MKLS0tIFNIL3VwdnpxZmN2d3R1OHp2dXVV
        UDFpTjJIWlczc3czSUx6Z0pGZjFRZ0EKKTbgin2WmuQ0B+PEusAtueFrXeAtkhtU
        OxuWP5nQA3d7lGd3dBQGRQ1XGByoa/4smITh946LaEksLIDubMjHJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T03:49:17Z"
  mac: ENC[AES256_GCM,data:CzaTfI9a+cuqMwIhwVu6MjE23XUjmQWZZxjqBnYQhWs4jj4ocY7mBLxJvH+D35opS2EKnrsh/3J0uzjC37FM8zeV7sGc+zcyljeksiL4Dt7WR4FjUCzgYF5uciNgWYxdY2N931w0FjfZIJPy0yloQRgwY0u+RbZmgwIKBhXrAz4=,iv:AOCiGoIz2RK0EYb36E40PX73B5Sh7D1mwbiPhFX5pjo=,tag:LjRX1vnREdwfcB4Ru7++FQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
