# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Z3ILJOxjupqwxwu0tJOovlSuP3HtZzLepm+XDB3D3LeVWVmDIZ0a5g==,iv:p9m7IColU5H+1RJ6ArOXNiSLVYqBi/bNO1bjZ62r4GE=,tag:q6lzELjEepFBf6l/N9rk8A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zhs8q2mkfm6a8pr6qlkklcgjkqzunluud63kr2z8vswk0v5u93esp4kj8e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjckN2RmdBaFhYVDBkbjFw
        bUVBVUlrT0tjajVEY2l2SVlidG9lZ2EwOFg0CmZkS090ak50MUFHSitoYW1MaGl6
        VDZ2U2U1L1FsNFdBRm9SeVp4YWRDcEkKLS0tIDF5eTVCM0I5V2VsYm0rWHFFNHFR
        RUpCM2MwVGNPdUlMUDZNR0VPWnl1YTAKS6mtwfxaoBTz9TPQbOjrFn3GfIoRA6zI
        HAbWIiFSsYQvW/rBedxJlB2Zrxhanrbdrh19EMFhSdw5eayCgvru7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T03:15:31Z"
  mac: ENC[AES256_GCM,data:Nhpic5Uk5BG3a02W9lJy4uGW4PZp+Iie8pIEy2xbLMHW8lXxEl7WaUTrmqi/+tEMRFtmrf8z+Es3v/MCc/vGuK6P6NzGrabqF8MTzZP0Ap37tJna5ReKrETDmC33bL/IYwQqFEnwah6NcMYbrfWTORhi6CzNbPVlwgZ6dTBZ51E=,iv:Op8dcNBLYitvliNNii6dl1f4pQEzkD+DPTLjySbr5vg=,tag:vyUd/giVAbzZWxC+bSUunQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
