---
apiVersion: v1
kind: Service
metadata:
  name: pgvector-r
  namespace: database
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: pgvector2
    cnpg.io/podRole: instance
---
apiVersion: v1
kind: Service
metadata:
  name: pgvector-ro
  namespace: database
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: pgvector2
    role: replica
---
apiVersion: v1
kind: Service
metadata:
  name: pgvector-rw
  namespace: database
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: pgvector2
    role: primary
  sessionAffinity: None
