apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:SbRY3majiXL1hP6qrsK1jIApFkY=,iv:CpRvwbn1TaUOxP6Sf/8pWezRjwJ4XhkvvVmr9OCWBPY=,tag:zElf8oJZnZsbPMDZwsE8+A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:pOfg7Pzc1I00a5VnIjm9BvpS0UKC8hfxoFwR5SD6broxdnko,iv:sEO8/eepsblioXqmICkLG/6IEX82yx01UEWKcpuXQ6c=,tag:PdzLV0iJMPLkxnUGa+LpmA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:Vf4LBZ2SlSf+vH2l,iv:T3ljvQRL2T2duJ8fEXxFNs3GYl9ZlYpH1WdmBNNezVs=,tag:fJrrCtFiXJc6pOsgk4VqUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbk40MHFuelN1YVpENWV0
            MGcvN2QxQkZWQzNnN0VVUDYxV1dML2dBeUhBCk9NWnNLRWhmWVNVdU5tM2ZKbmtO
            ekF2aVZkTTYrdUJvZGFHK1hLY2NUUmMKLS0tIEo3aVBhS2EwRUo5SDRWWDBPTWUz
            aTdDOVNKNHdEYjZMWkVxNmhCdFNMUHcKzBKqibsedIbJ1rAtSuvagFIBIqQqtGEX
            KRz9/Gcijy4uPb5x7vZDD4hXI/fP85LUif85EQPxSMxJdVNQN3mMsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T19:07:12Z"
    mac: ENC[AES256_GCM,data:lMFxJTT6LCoWDu+BfgmYKGUiKqgZMO28KOP6EAbWKXjvc9ycsCiv8rD0xna2E1gr/awnQ/43Ia1m9rWwc/3PpWsus5RW/Epf9FamfKJDEOol1hSF84Pww9Ir6v3LiVjBO2FQOv5fXYAiGFVRyvgLPVIrBrCzPzlYi+1z5DhYEME=,iv:gs57d9Zl6ysP3aIF7lKuAdCZ+QphhB15Ui14NhMT5oM=,tag:+EL9laiU0QDxs+zmfe9qBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
