apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:tk8SwauFofSLji47ncOsQTe6B1o=,iv:M0I/MiWJFe/J2NM3JX4b6nYHa81RHUbH/DzcnpO4Pgw=,tag:UfDJcLAE/2HVJSjKH68xsw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Z59sUkzBD5fw0ONsFqPQ3UNk/SaRM7BaO/FpVAzN5k4XWdBp,iv:z3gMkk5T4E5s5xp+9vWPbuccjyfAStzNKPHV5X7U46E=,tag:lq+C1U171y6KV1wcCsJYZA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:ezZsvnxlnAq1rKxf,iv:V7InrcjzCz3hb76f4igo38PEPUzZLoJX9tlVCffssqM=,tag:19DNf1gTXocJsaN5bDmU/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZ040THVTSjViZUtCSk1Q
            UjFCV1RpODFPOUtUSGRLU0VPZkNxaXdSNWlnClBwVStVVFZWd2JvWmdmeUF1a1pX
            aS9iTUxWSDdIMVlrdG1mVFBLWlJhUUEKLS0tIHZSRzJXMlFjajh4OVZVdkNwQjRy
            N1lweStnVkVNdy9MNFR0KzMyckZwTncKZtWaZfZL1Ai769e0Pe0K0o0wD1ASM5cn
            rB+CrcEaG4UkJQVxSghUup9vBeVpjL0+dj708yHPJqDduJs6nPQ8dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:25:26Z"
    mac: ENC[AES256_GCM,data:2gq68Re6Ky2/MQIFTExZtkrD2fpGJgxmEkqVqxgCxMpSsyqhfnLJTuV9xZy8aMp/BCb56OOienpcckX4BgzhhfPnM4WEHr0TUHWn2pVg8nTzz51ChvYSaa+8dbBcDHm/kHv03rq3wQ5jOL8JTGh6k5H9ls/5BIxHwEA2ekne7h8=,iv:TIrF2KRmLFV7JVLU5ZyiXZiNZweQqYz2VnnFsQkERLw=,tag:TLAl1QG92zaCl8hLPZB3qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
