apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:5/H47iz9mPDoi89Z,iv:/TY5D4qwUSpa++WaFBTi6ShkC9aB7qYlzkebgn00f+Q=,tag:Hf6s/D6yX6Od69g2Jb17ug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYWhSeStNZ2k4L2RudENC
            VEU5OThyK0JwbU5tYkRGRXFackZrb2x5UkFRCjJ2RVhJNDVsb2VONTBOelpkaUlH
            QUJ1cVFZd1NBZzZXeE1WZzh3eGJnNjgKLS0tIFNpa01HNWlIL2Y5bnBBN0xrY0xP
            Y3FkRk5KcjlmQUFxVThPRE9hWjc4VFkKRDpstLM7gzKYTNLfWHWo2eOVCEaJ3VYx
            LQTi02p1JzrizlEWVWwhP6ZlYjlX2LmbzZRdzyPRYsveK5VCO9EgLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:25:26Z"
    mac: ENC[AES256_GCM,data:Shn/j2KqOAlq8AbR9oSJ9h6MxQ29YM4KbBF6McJNZSN7NXao10RXbw+oOOCHm5VFQPKhhbsCcnIpiC3vGxfLpmNiAMBQXHSkxObP+tZAH4aiUJqch3xqOWuas9CplUEmI+8w6dgwlvvscLM/7bgkguLLCdMkoK2t8f0OKA3uM3U=,iv:4inGn1n8e3C+L7LRU/H+D1bv8kccdDYL+s1Br+oKJ0A=,tag:MRi3MAyuBMoUR6XMwX1XfA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
