apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:GRGWpSIAH6VMyqgt,iv:BGIjZOc7P5P79JZzZPn5NTuACWmH1p69vd+4FJbxYIU=,tag:EcLe8DTPgO1y5Ze9Y4z+oA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNDlHclpkSk5WNHlKV2JI
            blliVlkyZGN1NS9sNXEzck1UelZ1aXkxTFhnCmplRnhaWXNlOEZQZ01GYVA4Sm5K
            dXVOYWNnYk1mMHdxckd0NEtnUitMMHcKLS0tIGtWSDdna0h1WDkyM3ZQenh0ckFy
            cTBISFVUQWdtTXNRODlPMURyMXJQKzgKPomdXAkKCR8uCivk8+aWvKpdJy5cZlQI
            fDYyCqo2CiEoQk3A5ZwGf1RYRX+jNd0+HeMNW/yfNzgSBFFzrmb8cA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T19:07:12Z"
    mac: ENC[AES256_GCM,data:EPpBZP8ATssc1HT1J1pbLX8BbbQLYmopq1fEA2Jtow/cBrfbZB4CvUHyeoFYmIAXvTbINNYOXSsxGumPGKYZw21FpYJ5T/fqVQLhpBTx/YEg83s0i0L+zImdwlaJ/XSEaWX50D24SDXuA23fO4Pi2XbmKostre+eelARcjDl6LQ=,iv:xznAToRDH4VJO8XgqvNYMi4KANu2KrgzTzHfCe/jA5U=,tag:G6jsptKzNI32TV4FgpOWlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
