apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:QnunrKeCTv3HLYQ2xFQEhlhkSvI=,iv:jidi7M4/CWnNVPC4bpa6S9+azQ4vIiE/oIJyZ0PreEo=,tag:kqPm/YFLv3wFCuNVvbZtBg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:tA3kslcVvyLJzV4X8tRwsrszv9aC5SX25srBB5VLw1yecBWy,iv:I2kOPoQQMoiWWUmG8iu9JyHJAmWJ/E4Nthfk59gcMII=,tag:OoXBDH2fUL+YVx3qGu6A1g==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:gUoMyVFsr3Z83xfR,iv:jQKIyZCu08XgYc0jMCnbI6kl4XoTMXtPQ9tCq4z2V/w=,tag:enMnuGs3HRuSXhPk4qaoEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5b2JvQUszYWUwYXVQWG1X
            L0k1bVlRYlV2emt5K2VmMjVGVVF6R01zTGhBCkRiRmpYdXM1N3BSUENscS9ZUWhv
            Y1AyUGF4QS9Cc0p1aEY1dGtURTR1VFEKLS0tIHNXeUZ4eHVhSFNGcGhqbmg0WUxa
            ZnBWeWV2T3ZZMjFqWldHMTRQaW9wWFEKUEMcSJEOaKOYe5p9kGUjOZRF68KZm75z
            l7SJR8ZHMxt+6Wu+1YG2bgTa3M4ggL0c9JYiAG2dhqlexI1yx0x+Dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:46:24Z"
    mac: ENC[AES256_GCM,data:Hm6IXM9LrZMx9fxBrAKAoiE00e4Gzkw+8T3EvWJ0OS1V7XeMUTUkrD4AriUnmDvtGHrVUmQmntrP0aim7eVfauBNIu+axaQC4VvfKRHkpds3zom33v3W3GbAVZfGdSLAHASYBre9V8rgbzT1jRZXFS9FBojxeCJcXh0g89VcCOA=,iv:FS6AY9QtUJ8pwv/bl14JpOr9xFpO+smoG0QEp2LGpYY=,tag:wOQu5/ifxCqOVm4YCsOAWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
