apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:zgVCqyDlQV12u82s,iv:7ZrUlvkXNjSqjWHC/7N4unhEAisMp8+gIdZrec4k8sw=,tag:+Vga7FaHPhLArpiC8u3pZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNGJLekpybUpOMXZSaEZi
            NTRtL2Yzeldqc2ZHWGIxeFM5TVRCaXkxSHdFCk1WMW9YOGU3Z2l5YktkZU5Qcnh5
            VjZWR2V5ajQ3aEhnVjdtSVFLZ3ZRUVkKLS0tIHVUS0dCODA0RGQ0dVlyd2I1RFpR
            OVBhdHZRM0d3T0Y3V0Z1bEh0ZXZ1czgKzGX4LJ0HGZjkD8H1a2vI3MD6923n4at7
            Nzr28eFEu75970LrX7HjH7XG8+dmNzUND5E10FICTyM8DpxIJvOYzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:46:24Z"
    mac: ENC[AES256_GCM,data:S02mjbE9lR2f0OCW4IYIR+Kf1ENpj7nsK2zYtXM2nbr+T2yW7xunipXcybZp6o92qecaerWkD8qjOQ9e/lDV/uzG3yU6RKW37nNDAP34dzYgzCwwYD/Oq0sW1Z2yMMJOwlcfzt9AtUvFdgS2goVc8qqp/LCIh+lCyAzoOqZEpcQ=,iv:gjmxL0pO+6wVx/h4qQtTxFWtmNDcu7iJkHCNCss6fec=,tag:/XGA68ddKxGuxmu31VwoAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
