apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:I4xIDGGYy6tqKecKlC10cvJkWJsoXhmA/LXZGfb9vc1Ceyhj,iv:JRlT8iqrX+4GcD3syyN3CLOi3YOvde8BLC4moUf3YxQ=,tag:R3YHhuS1f0aEfHe4BB2H+Q==,type:str]
    credentials.json: ENC[AES256_GCM,data:R3SPHHLrCUUyAn9CQkI+W+by8vRVfUtOqS+XhGyAriQz21ZYKXyQ9GQlkzcMm3fgFjZRnSKQq1yUPgJcH7cwJmJLZ8aqTK3PbTAa9uYuSS4FKzn5ZiuwBnzyjPMI0111C0W2C+XK3cdYOH6fwKEtZIZ6TcgdtkdcNYDjTYa1KAsdwXgZf79QG6ar41vOzMpdvgvfsExrAY3TUAcZ4wdr1LiqbUkJAYuNit5ONZ4GbQ==,iv:Z3/Ie9dZSHlOWeodq2LAicQXwVnqpjxBxaWZgNDIbQ0=,tag:1ZYn35C6Pz1Ek5yUil9Bxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2QWQ1NXUxcTNNS04vU0RR
            a1I1RG1mSFViRy9vMmJJemhKY2xvYW95Ymk4CnUxUkR5eFFvRUxCb2piK3FJL091
            SURxa1VZak9zN0VidDhnWEJFaWtURnMKLS0tIGd6a2lsRG10cGF4N1dhejliQ05F
            VjEvb3p4YlVmNGw4UkZSdHRpNlRvS1kK4Q8mf3LRQL1G19twXshpl0CU0MCZrYyE
            5gXBFkiPjKYWA+Ve9EIsQYpQ/oEgskoRxXr56yiefxbWPlOFC5lPOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T19:07:13Z"
    mac: ENC[AES256_GCM,data:nnvEWWYbtFdb8ZtH7Q9Buk1+Zie1dwLV6O9zSKCRMmQzZcozYCRs4/C7WQ/o7LlJqLc39gGmD8HnNPuOQ/PrNpjd0bLfwvWwOGYzWoi78xEPeH/NkWqZW4swnN8Rre/IdwnuPJ+gI64JMrS+LoeJ3SRewg48KjVy1L4KM8c34q8=,iv:7WZLAr6G/snEcQ/TcJV8UheTQ9sdJxNpZfFyi+vN0WU=,tag:epT4KfqkSu1tqHGDkJbO3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
