apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:FDGo7qylJWuUCjX1ntfYTjyBM9YtqYYqH2ycbU7VlFXR+r2C,iv:zt4NdGxR3Uz5W8U5iGHvlJQjN+8wcWU+s+7lwVvSBxc=,tag:mxHDOXTx1XFnr0EEhuTZ4w==,type:str]
    credentials.json: ENC[AES256_GCM,data:1A615Sh/2tUd6vMzSFSnBME4lvxe5UhFkI1lIwDjzMlRHb8O2lv+i35BQmUuBd1UzrnKGEeADTyAxK4i6PXQ7YkSu0uW06+Vv8pf00Fp92re8qdrkZ3/Ufj6OOMNxJpMPO/KBSaw5HkFPFKoyCr3ypWH4+U7KD3uJ3EOGWqgMS3oWvcWexmozqrHCh+AQJJ3ADA46TMoNimiwkYCxXMF7zMBECDHLcsAs8SIgKacag==,iv:hy4xl+CxSrVoEcvFk3untMcPWPWNTFJyLFQq+2l1hPA=,tag:HbuzqB2EyHjjekpo5rrTGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRTU3bDh5dGxWenN0V3pD
            RzRqTXU2T1FCc2NBOFNCMXZ6bmdNMkU3QUdzClNFM2Ywd2JDaS9RYnM2S3dZTlpl
            a00zSnB1Rk5GVGpIY2R4MTVWTG9mU0kKLS0tIFR2U3lvUG5CQ3J3TUlkSjRmR041
            dGlmcG1Wd0prNmRBQnB1bkV1R2N2YncKWw2yrC/nsjaNrolS8Ohm6yxhqJ23IQDx
            DSWRb8aXFPEN+ia13xNoNCrkISzsfEoWmhPw5DsHlWysPcFvmxh+MA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:46:25Z"
    mac: ENC[AES256_GCM,data:dNVvQueJ6Y7KOvOsakqxvyX3CKKhngojXTuQvMg9R+wCreuYeWPTOipEhQ3x2LaqV0nhvjTKK4vnG+d14L7a6ZaDqnQndJmBl3R/r0I6zl8+73Jm+0+6pz0joGiIF5mSUD/Iq2i2M6W4gawoKZfNxexMW8h4CQl8Gbgl0vREMBY=,iv:lOUf72G5/ZbMvfq7SEtAVYsLyZqD+CvP0taUnaIKJGE=,tag:H9ZgvdXm3a8PckhCVN6Txw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
