apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:MhYis9imqRLZXGN4GiP3KLqPgYWqEmHlpJZCFsBmykC6l7Zf,iv:I7A2Ye7SREnFO972v4nWATubLZJsETL+T71knCzD/oo=,tag:tgW3yVWf3ZoGWOyLyBjU9w==,type:str]
    credentials.json: ENC[AES256_GCM,data:xmCw6PTRunLmUCQEjilD9fL7kxEsXC9dT7NOqESQxfeuy0eMViCqXT9TSoOlOihsYHZu91Jb46+lrk2tr2U9PilepQIIf5FgaF+Yoc4PdOYY0EmxqGZlAWH2z+OVoPOwZbw5q/gmeIoKHaajESMlePlIo1BPSPSsJcuY3K52HB+uGQQ8339iaEPTKjibDvwROAKkc+Mj4gv6EWNou9fIpm0l82Nh8tRgAbdhwLF7Tg==,iv:zssQepwAKxcHKBF0kRiA98+UzCb9doWM8d56WKkO1Tc=,tag:hWc7LRhJdhnUo8aNCEmlBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grr4uy5euhgfzzjgygrvwqw2dv7s7uwv49yue83ckyazw5eveetqda8g63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQThiOXdxekNMbUhRaTVi
            dFpLaWJWMFExbTR1WWIrdENQMmliR1V5a1NRCk02Nk12SkIwUjdaclBOcEpjOFUr
            ODMwWU40ZjNjN1JyZ3NMdUVDYVA3QWsKLS0tIG44cDZYdVVWREFXVWFIUHNsOVZs
            RTd3RFJUOG4vWE1EVGh5TUdOYUtId00Khk5saLEnhNA6Ey/7Nkv6z4InRTb7w+Xs
            nIIk6tt4aFwsXikQ/6HtazTCEWD/dSFI6PdZmwvL+tfWxTmlSoz5TA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:25:27Z"
    mac: ENC[AES256_GCM,data:IH1LdZ0F21MxqOkSHj7t31+Tci68aR2eK1xI5Pg/scAyDoFHQdhJSAU3RLG0hmpuz/N4/71BKcmMyedIXBHCwJckaEbMvEl6kpRu27LSSJPWHJIzJXC+UkSziTANrcvdB7u6WzYU335f1HnoVzQzREh45wsEy4UCg6jiVVOHlEY=,iv:aAjUyz+z6LeNTxhwoTQT8aJ7hUCTdGXXWUFzuP5CVpI=,tag:KoCJXrRa5FM6ZHeYmOY5qw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
