---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: democratic-csi-nfs
  namespace: kube-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: democratic-csi-nfs-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels: {}
  data:
    - secretKey: truenas-username
      remoteRef:
        key: democratic-csi-nfs
        property: TRUENAS_USER
    - secretKey: truenas-password
      remoteRef:
        key: democratic-csi-nfs
        property: TRUENAS_PASS
